services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - symfony_tp_db:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  symfony_tp_db:
networks:
  app-network:
    driver: bridge
